// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfcezkcmpeadbnrpjctx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmY2V6a2NtcGVhZGJucnBqY3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjAyMDgsImV4cCI6MjA3MzczNjIwOH0.5RkWqL0y0icV_psTi5s8zp0Xs1FJgc9IfnbnsR5GTVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});